Sequelize HowTo
aws-samples/aurora-dsql-samples pull request #102
Opened 2024-12-10 20:54 UTC by mitchell-elholm

By submitting this pull request, I confirm that my contribution is made under 
the terms of the MIT-0 license.

Thank you for your contribution!

2024-12-10 20:57 UTC, alinaliBQ commented on .github/workflows/typescript-sequelize-integ-tests.yml
> +        REGION: ${{ secrets.TYPESCRIPT_SEQ_CLUSTER_REGION }}
```suggestion
        CLUSTER_ENDPOINT: ${{ secrets.TYPESCRIPT_SEQUELIZE_CLUSTER_ENDPOINT}}
        REGION: ${{ secrets.TYPESCRIPT_SEQUELIZE_CLUSTER_REGION}}
```

2024-12-10 21:00 UTC, alinaliBQ commented on .github/workflows/typescript-sequelize-integ-tests.yml
> +  test:
```suggestion
  sequelize-integ-test:
```

2024-12-10 21:31 UTC, alinaliBQ approved these changes
LGTM

2024-12-10 23:37 UTC, lmarcosi approved these changes

2024-12-10 23:55 UTC, alinaliBQ requested changes
Please also update the root [README.md](https://github.com/aws-samples/aurora-dsql-samples/blob/main/README.md) to include the TypeScript HowTos

2024-12-11 00:37 UTC, alinaliBQ approved these changes

2024-12-11 00:47 UTC, merged